[package]
name = "spdk-rs"
version = "0.1.0"
authors = ["xxks-kkk <ferrishu3886@gmail.com>"]
#edition='2018'

[dependencies]
libspdk-sys = { path = "libspdk-sys" }
failure = "0.1.2"
libc = "0.2.43"
futures-await = "0.1"
#futures-preview = "= 0.3.0-alpha.7"