[package]
name = "hello_nvme_bdev_rust_wrapper2"
version = "0.1.0"
authors = ["xxks-kkk <ferrishu3886@gmail.com>"]

[dependencies]
spdk-rs = { path="../../spdk-rs"}
futures-preview = "0.3.0-alpha.7"
tokio-core = "0.1.17"
failure = ""
failure_derive = ""