[package]
name = "benchmarks"
version = "0.1.0"
authors = ["xxks-kkk <ferrishu3886@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.4.10"
spdk-rs = { path="../spdk-rs"}
failure = ""
failure_derive = ""